services:
    auth-ms-colegio:
        container_name: auth-ms-colegio
        image: auth-ms-colegio
        build:
            context: ./auth-ms/
            dockerfile: Dockerfile
            #./auth-ms:/workspace/app
        ports:
            - "8090:8080"
        networks:
            - colegio-network
    mysql:
        image: mysql
        container_name: mysql-auth
        ports:
            - "3390:3306"
        networks:
            - colegio-network
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: auth
            MYSQL_USER: root-auth
            MYSQL_PASSWORD: 12345


#red para poder conectar todos nuestros contenedores
networks:
    colegio-network:
        driver: bridge

#persistir datos y no se pierdan
volumes:
    mysql-volume:
        driver: local